#pragma once
#include <iostream>
#include <Windows.h>
#include <iostream>
#include <Windows.h>
#include <string>
#include <sstream>
#include "Shlobj.h"
#include <tuple>
#include <stdexcept>
#include <vector>
#include <queue>
#include <functional>
#include <memory>